### ISSUE TITLE
使用mip-map组件时，页面上存在输入框focus时报错

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2-extensions#159]
**BUG 描述**
当页面上引用的mip-map组件时，input 输入框 focus报错

**复现步骤**
访问：https://m.jikexiu.com/resources/mip/order.html?categoryId=12-12
点击输出凯获得焦点，
页面报错

**截图**
![image](https://user-images.githubusercontent.com/3196280/43447533-487efb12-94de-11e8-8fbd-abee5bce90a1.png)

排查代码发现
mip2核心代理了input的focus事件，此时会向parent发送message, 
![image](https://user-images.githubusercontent.com/3196280/43447680-93a5d0f2-94de-11e8-895a-9ad772cc8966.png)

地图sdk的代码里，有全局监听message事件的逻辑
调用了JSON.parse，但是没有try catch

![image](https://user-images.githubusercontent.com/3196280/43447754-c19895b2-94de-11e8-9241-e580cd07b89e.png)

**Comment by PengXing** [comment]
`rate` 报错的问题，我已经提交修复代码了 https://github.com/mipengine/mip2/commit/31343b1e59d9bee59614c32d6696a25a768169d9

待下次 mip2 核心代码上线之后就不会报错了，但是 `rate` 报错并不是导致功能不好使的原因，还需要组件开发者跟进

**Comment by VenyXiong** [comment]
地图报错的原因已经反馈给地图SDK团队，后续单独跟进他们那边的修复进度

**Comment by PengXing** [comment]
那这个 ISSUE 我就关掉了
