### ISSUE TITLE
在mip-form中添加校验的功能点

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2-extensions#225]
**要解决什么问题**
目前在mip1中会有站长提出针对mip-form的表单的校验的功能点；
issue地址：https://github.com/mipengine/mip-extensions/issues/1213

**描述一下你理想中的解决方案**
希望在mip2的form组件中集成类似的功能点；
比如：如果内部的输入框设置必选项，在form点击提交时，可以进行错误信息的定位；

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by clark-t** [comment]
closed as timeout
