### ISSUE TITLE
mip-list 组件迁移不彻底

### ISSUE THREAD

**Issue by chenqiushi** [mipengine/mip2-extensions#296]
**要解决什么问题**
#265 mip-list 组件迁移不彻底。mip-list 组件使用到了 v1 版本的 mip-mustache 组件（没有迁移），使用时需要引用 v1 的 mip-mustache.js 和 v2 的 mip-list.js。

**描述一下你理想中的解决方案**
迁移 v1 的 mip-mustache 至 v2

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
![image](https://user-images.githubusercontent.com/5038140/47007896-cd3f8c80-d16b-11e8-9d0c-8ead78e7fafa.png)

**Comment by allen886** [comment]
https://c.mipcdn.com/static/v2/mip-list/mip-list.js 改成这个了 还是不行啊

**Comment by allen886** [comment]
![image](https://user-images.githubusercontent.com/23253054/48314474-05b87600-e605-11e8-804d-6b2496bf6c03.png)
这个是什么错误啊 ？？

**Comment by PengXing** [comment]
timeout，这里写的还是很清楚了
