### ISSUE TITLE
在非百度分发环境中，网盟广告和凤巢广告切换展示需求

### ISSUE THREAD

**Issue by wqllpw** [mipengine/mip2-extensions#302]
**要解决什么问题**
因为凤巢广告无法在非百度分发环境中正常展示，为了保证这部分广告对于用户的收入，需要能够切换到网盟广告

**描述一下你理想中的解决方案**
考虑新增组件，包装切换业务逻辑

**描述你的备选方案**
在原凤巢组件上修改，增加切换逻辑

**补充信息**
无

**Comment by wqllpw** [comment]
可能还有其他类似的组件问题，能否一并梳理解决？

**Comment by VenyXiong** [comment]
这里我理解后续面对这种场景我们是需要有一个这样的组件进行环境区分，
<mip-env>

**Comment by VenyXiong** [comment]
这里应该是有这个需求的。
<mip-env>
    <mip-fc-ad scope="baidu"></mip-fc-ad>
    <mip-wm-ad scope="all"></mip-wm-ad>
</mip-env>
但是需要明确下检测运行环境的规则，
目前来看用cdn的域名是不是一种比较合适的方案？
这里确认下环境的检测规则，没问题应该就可以介入开发了。

**Comment by VenyXiong** [comment]
好像有一部分没有展示出来，这里新增环境检测的组件似乎更合理一点，通用性也更强一点。
写法形式上类似这样
`<mip-env>
<mip-ad-baidu scrop = "baidu"></mip-ad-baidu>
<mip-content scrop = "all"></mip-content>
</mip-env>`

**Comment by wqllpw** [comment]
> 好像有一部分没有展示出来，这里新增环境检测的组件似乎更合理一点，通用性也更强一点。
> 写法形式上类似这样
> `<mip-env> <mip-ad-baidu scrop = "baidu"></mip-ad-baidu> <mip-content scrop = "all"></mip-content> </mip-env>`

可行，分发平台负责自己业务的环境逻辑配置

**Comment by tayqassqan** [comment]
汇总一下之前讨论的方案结论：

## 组件功能需求
提供语义化的环境判断功能，可让开发者通过语义化的方式配置组件是否执行。

## 方案设计
在方案设计时主要考虑组件的应用范围和配置方式。

### 应用范围
不同环境下出现不同广告是组件的其中一个应用场景，依赖的是cache和分发平台的运行环境。此外，可能有额外的运行环境检测需求，例如：UA或OS。

基于此，组件的使用范围可以不局限于cache或分发平台的运行环境检测与判断。在设计上考虑提供多种运行环境的检测与配置方案。当前设计考虑以下运行环境的检测：

- Cache
- Distribution platform
- User Agent
- Operating system

后续如有需求可以继续添加。

### 配置方式
由于存在多种环境的检测并且在将来可能进行拓展，因此提供给开发者的配置应尽量通用，利于拓展。

配置方案设计如下：

1. 组件名
通过`<mip-env>`的方式使用组件

2. 环境判断配置
通过在`<mip-env>`中添加属性完成配置，属性名为`scope`，示例：`<mip-env scope={"cache": "baidu","dp": "baidu","ua": "UC", "os": "IOS"}>`。

3. 识别规则
scope中的环境变量依赖识别规则，识别规则可通过组件文档进行统一，并在实现时符合文档中的规则描述。

**Comment by zidanDirk** [comment]
这里的Cache具体指的是什么，组件的使用方如果确定这个cache的值

**Comment by zidanDirk** [comment]
> 汇总一下之前讨论的方案结论：
> 
> ## 组件功能需求
> 提供语义化的环境判断功能，可让开发者通过语义化的方式配置组件是否执行。
> 
> ## 方案设计
> 在方案设计时主要考虑组件的应用范围和配置方式和运行方式。
> 
> ### 应用范围
> 不同环境下出现不同广告是组件的其中一个应用场景，依赖的是cache和分发平台的运行环境。此外，可能有额外的运行环境检测需求，例如：UA或OS。
> 
> 基于此，组件的使用范围可以不局限于cache或分发平台的运行环境检测与判断。在设计上考虑提供多种运行环境的检测与配置方案。当前设计考虑以下运行环境的检测：
> 
> * Cache
> * Distribution platform
> * User Agent
> * Operating system
> 
> 后续如有需求可以继续添加。
> 
> ### 配置方式
> 由于存在多种环境的检测并且在将来可能进行拓展，因此提供给开发者的配置应尽量通用，利于拓展。
> 
> 配置方案设计如下：
> 
> 1. 组件名
>    通过`<mip-env>`的方式使用组件
> 2. 环境判断配置
>    通过在`<mip-env>`中添加属性完成配置，属性名为`scope`，示例：`<mip-env scope={"cache": "baidu","dp": "baidu","ua": "UC", "os": "IOS"}><mip-ad></mip-ad></mip-env>`。
> 3. 识别规则
>    scope中的环境变量依赖识别规则，识别规则可通过组件文档进行统一，并在实现时符合文档中的规则描述。
> 
> ### 运行方式
> 如上述配置方式描述，组件的运行方式为：
> 
> 1. 默认不执行组件内部HTML内容；
> 2. 组件`build`或`firstinviewcallback`时进行组件`scope`属性的配置匹配；
> 3. 如果当前环境与`scope`中声明的规则描述一致，则执行组件内部HTML；

这里的Cache具体指的是什么，组件的使用方如果确定这个cache的值

**Comment by tayqassqan** [comment]
Cache指的是当前页面的Cache环境，比如'mipcdn'或'smcdn'

**Comment by html5david** [comment]
> Cache指的是当前页面的Cache环境，比如'mipcdn'或'smcdn'，或者是nocache

cache是否可以归到dp中，使用者可能并不关心或知晓各平台所使用的cache，当dp=baidu时，所使用的cache也应该是baidu的吧。

**Comment by tayqassqan** [comment]
还是不太一样，因为分发平台可能不止是搜索，也可能是feed，所有这里还是需要cache和dp的不同区分。

**Comment by html5david** [comment]
> 还是不太一样，因为分发平台可能不止是搜索，也可能是feed，所有这里还是需要cache和dp的不同区分。

目前我这边是根据当前域名来识别dp是否符合条件，eg: 
dp = baidu ->  ['mipcache.bdstatic.com', 'c.mipcdn.com']; 
dp = sm -> ['sm-tc.cn']

Q 1、查看当前域名是否符合传递过来的dp。  dp这样处理OK吗？
Q 2、能否给举个检测cache是否符合条件的例子？
