### ISSUE TITLE
多图轮播组件宽高自适应能力

### ISSUE THREAD

**Issue by gentlemanwang** [mipengine/mip2-extensions#320]
**要解决什么问题**
多图轮播组件，可根据图片高度判断容器高度，以支持图片正常展示不被拉伸变形

**描述一下你理想中的解决方案**
·多图轮播组件<mip-carousel>支持根据图片高度，切换图片时自适应调整高度

**描述你的备选方案**
·多图轮播组件<mip-carousel>高度固定时，图片可在组件容器内匹配高度正常展示不拉伸，图片宽度小于页面宽度时两侧留白

**补充信息**
备选方案示意图：
![image](https://user-images.githubusercontent.com/9955853/47779269-ad939100-dd33-11e8-92db-c330776d8b0d.png)

**Comment by craigchencc** [comment]
需求明确一下：除了上图的展示结果，自适应的效果应该还包括宽度 100% 高度不够上下留白的情况，也就是 `background-image` 的 `contain` 效果。

用法：`mip-carousel` 组件还是原来的写法，需要加个参数表明是 `contain` 效果，暂定 `contain="contain"` 。

实现方案：读取 `mip-carousel` 组件原来的子节点 `mip-img` 的 `src` 后删除 `mip-img` ，另实现带 `background-image` 的 `div`，从而实现 `contain` 效果。

副作用：需要修改图片懒加载的代码，因为当前代码并没有对  `div` 的 `background-image` 进行处理。

**Comment by craigchencc** [comment]
上述解决方法略显繁琐，由于 `mip-carousel` 组件可以渲染非 `mip-img` 元素，所以可以直接利用 `div` 实现，代码示例如下：
```html
  <style mip-custom>
    .contain1,
    .contain2,
    .contain3,
    .contain4 {
      background-repeat: no-repeat;
      background-size: contain;
      background-position: center;
    }
    .contain1 {
      background-image: url(https://www.mipengine.org/static/img/sample_01.jpg);
    }
    .contain2 {
      background-image: url(https://www.mipengine.org/static/img/sample_02.jpg);
    }
    .contain3 {
      background-image: url(https://www.mipengine.org/static/img/sample_03.jpg);
    }
    .contain4 {
      background-image: url(https://www.mipengine.org/static/img/sample_04.jpg);
    }
    .gray {
      background-color: #ddd;
    }
  </style>
<mip-carousel
  layout="responsive"
  width="600"
  height="400"
  class="gray">
  <div class='contain1'></div>
  <div class='contain2'></div>
  <div class='contain3'></div>
  <div class='contain4'></div>
</mip-carousel>
```

这是效果图：  
![carousel](https://user-images.githubusercontent.com/41358202/48324003-06372800-e66a-11e8-8c28-a02a21153dc0.png)

所以根据这种方法可以不用修改 `mip-carousel` 组件，利用上述类似的代码就可以完成本 issue 的要求，而且用户还可以自定义背景的颜色或其他样式。

另外针对这种方法没有图片懒加载的问题，最近会增加一些代码来解决这个问题。

**Comment by PengXing** [comment]
使用 css 设置 `background-image` 没法用 JS 来控制吧

**Comment by LiuXin0807** [comment]
> 使用 css 设置 `background-image` 没法用 JS 来控制吧

这里需要服务端渲染， 在css里 走一个遍历就出来了
