### ISSUE TITLE
mip-video 引用 v1/mip.css v1/mip.js 有视频默认图 引用 v2/mip.css v2/mip.js 没视频默认图

### ISSUE THREAD

**Issue by liushaokai** [mipengine/mip2-extensions#372]
![default](https://user-images.githubusercontent.com/9527526/49495332-a2d19c00-f89d-11e8-918b-05d4b29af42e.png)

**Comment by liushaokai** [comment]
https://m.miaoshou.net/mip/video/669881.html

**Comment by craigchencc** [comment]
功能已修复，进展在[这里](https://github.com/mipengine/mip2/issues/385)，所以这个 issue 就关闭了
