### ISSUE TITLE
增加pull reaquest netlify预览

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip2-extensions#4]
目前的PR： https://github.com/mipengine/mip2-extensions/pull/2

可以考虑改成这样子：https://github.com/mipengine/mip-extensions/pull/1169

![image](https://user-images.githubusercontent.com/8498677/40764163-849f8c12-64da-11e8-82bc-941998944429.png)

**Comment by chenqiushi** [comment]
已经接入 netlify 自动部署预览。

**TODO**:  换成    ###**mipengine-bot** 帐号
