### ISSUE TITLE
【项目-MIP官方组件迁移】医疗页面showmore组件展示异常

### ISSUE THREAD

**Issue by gaoshan003** [mipengine/mip2-extensions#481]
**BUG 描述**
医疗页面showmore组件展示异常
![image](https://user-images.githubusercontent.com/39788046/51531438-67eced00-1e78-11e9-88df-88633f937c5b.png)

需要修改mip核心

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by PengXing** [comment]
https://github.com/mipengine/mip2-extensions/pull/482

在这个 PR 中修复了
