### ISSUE TITLE
【项目-MIP官方组件迁移】mip-appdl，IOS下，UC浏览器链接不能跳转

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#496]
**BUG 描述**
【项目-MIP官方组件迁移】mip-appdl，IOS下，UC浏览器链接不能跳转

**复现步骤**
重新复现 Bug 的步骤
1.点击【立即使用】
2.没有调起链接到下载

**截图**
![image](https://user-images.githubusercontent.com/46017563/51740072-fad29500-20cd-11e9-9b31-464cd6d993ac.png)

**环境及版本信息:**
IOS
浏览器：UC浏览器
@Brunoon

**Comment by Brunoon** [comment]
这个 v1 也是这样的，目前还没找到解决方法，暂时先不修复
