### ISSUE TITLE
【项目-mip-map迁移2.0】IOS 8中三维的内容显示不出来

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#512]
**BUG 描述**
【项目-mip-map迁移2.0】IOS 8中三维的内容显示不出来

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
![image](https://user-images.githubusercontent.com/46017563/52698854-5b5b4080-2faf-11e9-8d87-2528f82ef393.png)

**环境及版本信息:**
IOS 8

**其他信息**
测试地址：https://www.mipengine.org/validator/preview/s?url=https://deploy-preview-469--mip2-extensions-preview.netlify.com/examples/mip-map/mip-map.html

**Comment by Brunoon** [comment]
这个是百度地图 api 的问题，在[api](http://lbsyun.baidu.com/jsdemo.htm#b0_3)也显示不出三维图
