### ISSUE TITLE
【mip-viz-echarts 】IOS8 、IOS10、IOS12排序错乱； IOS11、IOS12  简单搜索、QQ点击下载按钮，无法下载图片

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#517]
**BUG 描述**
1.iPhone 7P（IOS10）、iPhone XR（IOS12）、iPhone 5s（IOS8）排序错乱（如图）
2. IOS11、IOS12  简单搜索、QQ点击下载按钮，无法下载图片

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
![image](https://user-images.githubusercontent.com/46017563/52854829-c006ce80-315a-11e9-867d-e04d1bfac9ef.png)
![image](https://user-images.githubusercontent.com/46017563/52854854-cd23bd80-315a-11e9-8606-243ac02a8919.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by zoumiaojiang** [comment]
由于 echarts 对移动端支持不友好并且不支持纯 JSON 数据驱动，所以准备采用和 AMP 同样的 vega 方案进行替代 echarts，所以将用 mip-viz-vega 替代 mip-viz-echarts，这个 issue 先关掉，转到 #324
