### ISSUE TITLE
mip-fixed 层级不可修改，致使页面层级出现问题

### ISSUE THREAD

**Issue by wangyinqian** [mipengine/mip2-extensions#522]
**BUG 描述**
清晰和准确的描述 Bug 是什么
mip-fixed自动计算z-index，无法手动修改。这致使我们网站Header、Footer、Nav三个控件的层级出现了问题，Header、Footer的层级高于Nav，盖住了Nav的首项和尾项。
**复现步骤**
重新复现 Bug 的步骤 4

**期望结果**
清晰和准确的描述你期望的结果
我希望mip-fixed的层级可以通过人为来进行控制。
**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**  Browser
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by PengXing** [comment]
z-index 的大小根据元素在 MIP 页面出现的顺序从上到下的，你可以调整一下自己页面里的元素顺序
