### ISSUE TITLE
【mip-custom】页面底部部分内容被底部按钮遮挡

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#533]
**BUG 描述**
【mip-custom】页面底部部分内容被底部按钮遮挡
测试地址：http://cp01-sys-rpm14.cp01.baidu.com:8003/mip/c/s/m.120ask.com/askg/mip_detail/69956476?s_j=1

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
![image](https://user-images.githubusercontent.com/46017563/53334899-04515600-3935-11e9-8137-7bd4f68b9b96.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by gaoshan003** [comment]
已修复
