### ISSUE TITLE
【mip-custom】点击能跳转的部分，页面js报错

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#534]
**BUG 描述**
【mip-custom】点击能跳转的部分，页面js报错
测试地址：http://cp01-sys-rpm14.cp01.baidu.com:8003/mip/c/mip.club.xywy.com/mip/20170706/128912501.htm?s_j=1

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
![image](https://user-images.githubusercontent.com/46017563/53335014-52fef000-3935-11e9-934a-6aaea003b90b.png)
点击红框标出来的地方
![image](https://user-images.githubusercontent.com/46017563/53335080-73c74580-3935-11e9-89b4-96399a2c9998.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by gaoshan003** [comment]
已修复
