### ISSUE TITLE
mip-stats-google v2 缓存没有更新

### ISSUE THREAD

**Issue by halfer53** [mipengine/mip2-extensions#561]
**BUG 描述**
mip-stats-google 适用于 Google Analytics的MIP组件
V1地址：https://github.com/mipengine/mip-extensions-platform/tree/6ef473eb6a440d8dc16bf9d040e631e01396a5f6/mip-stats-google
v2地址：https://github.com/mipengine/mip2-extensions/tree/master/components/mip-stats-google

但是CDN下v2的代码还是跟v1一样，并没有反映最新的代码。
https://c.mipcdn.com/static/v2/mip-stats-google/mip-stats-google.js

**复现步骤**
访问v2的mip-stats-google，但是跟v1的代码一样
https://c.mipcdn.com/static/v2/mip-stats-google/mip-stats-google.js
https://c.mipcdn.com/static/v1/mip-stats-google/mip-stats-google.js

**期望结果**
https://c.mipcdn.com/static/v2/mip-stats-google/mip-stats-google.js
应该是最新的v2 mip-stats-google的编译结果

**Comment by Ricardo-Li** [comment]
目前已更新，应该是上周没有上线，官方组件每周四上线更新。

**Comment by halfer53** [comment]
昨天mip更新以后， v2 的 mip-stats-google 的缓存又变成 v1 的了。

https://c.mipcdn.com/static/v2/mip-stats-google/mip-stats-google.js

@Ricardo-Li
