### ISSUE TITLE
【mip-form组件】 【加清空按钮】下，在输入框中输入内容，点击清空按钮，此时输入框中无法再输入内容

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#571]
**BUG 描述**
【mip-form组件】 【加清空按钮】下，在输入框中输入内容，点击清空按钮，此时输入框中无法再输入内容

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
![image](https://user-images.githubusercontent.com/46017563/54739460-24ea9400-4bf3-11e9-870b-c84a60f79086.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by Ricardo-Li** [comment]
在 UIWebview 两次 touch 事件会导致无法输入文本。https://github.com/mipengine/mip2-extensions/pull/570/commits/8ac0da10b31b2f9aa4d06d75822fbe81ababe1fd


修复方法参考 https://stackoverflow.com/questions/13124340/cant-type-into-html-input-fields-on-ios-after-clicking-twice。
