### ISSUE TITLE
【mip-form组件】 IOS8（iPhone5s） 中点击【提交】按钮都没有反应

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#573]
**BUG 描述**
【mip-form组件】 IOS8（iPhone5s） 中点击【提交】按钮都没有反应
测试地址：https://www.mipengine.org/validator/preview/s?url=https://deploy-preview-570--mip2-extensions-preview.netlify.com/examples/mip-form/mip-form.html

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
IOS8

**其他信息**
其他补充信息

**Comment by Ricardo-Li** [comment]
https://github.com/mipengine/mip2-extensions/pull/570/commits/8ac0da10b31b2f9aa4d06d75822fbe81ababe1fd

避免使用 forEach，在低版本 iOS 存在问题。
