### ISSUE TITLE
【mip-form】组件【自定义校验规则】当输入框什么都不填入的时候，可以直接提交

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#574]
**BUG 描述**
【mip-form】组件【自定义校验规则】当输入框什么都不填入的时候，可以直接提交
测试地址：https://www.mipengine.org/validator/preview/s?url=https://deploy-preview-570--mip2-extensions-preview.netlify.com/examples/mip-form/mip-form.html

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图
![image](https://user-images.githubusercontent.com/46017563/54749767-9422b100-4c10-11e9-8ab9-1f25e52463f4.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by Ricardo-Li** [comment]
fix: https://github.com/mipengine/mip2-extensions/pull/570/commits/882a0ecb09031a7ba9ee4945f82d1a071d607998
