### ISSUE TITLE
【mip-form】组件，IOS12（iPhone 6s）简单搜索、UC 点击输入框不输入内容，点击输入法上【完成】，下面出现一片白色蒙屏

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2-extensions#575]
**BUG 描述**
【mip-form】组件，IOS12（iPhone 6s）简单搜索、UC 点击输入框不输入内容，点击输入法上【完成】，下面出现一片白色蒙屏

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
IOS12（iPhone6）

**其他信息**
其他补充信息

**Comment by Ricardo-Li** [comment]
简单搜索仅在 iOS 12 下有问题，软键盘收回后有空白，推测与 webkit 有关。修复方式要改变外层页面高度或触发 scroll，改变 iframe 内页面属性无效果。

参考：

* https://github.com/apache/cordova-ios/issues/417
* https://developers.weixin.qq.com/community/develop/doc/00044ae90742f8c82fb78fcae56800

UC 浏览器表现不一致，input focus 时被遮挡，软键盘收回后无空白。
