### ISSUE TITLE
【增强 mip-map 功能】IOS8（iPhone5s） 中点击按钮无反应

### ISSUE THREAD

**Issue by liujing50** [mipengine/mip2-extensions#587]
**BUG 描述**
IOS8下，点击”看看博物馆和大剧院“按钮无反应。
测试地址：https://deploy-preview-586--mip2-extensions-preview.netlify.com/examples/mip-map/mip-map1.html

**复现步骤**
重新复现 Bug 的步骤
1. 打开页面
2. 首次点击按钮地图移动正常
3. 点击”去天安门广场“功能正常
4. 再次点击”看看博物馆和大剧院“，无反应。

**期望结果**
按钮正常响应

**截图**
![52B1D200AF6A136C76681ED57581DB83](https://user-images.githubusercontent.com/48906158/55462495-78b0a080-5629-11e9-9c31-25db58ba6e45.JPG)

**环境及版本信息:**
 - IOS8
 - Browser: Safari, 手百

**其他信息**
其他补充信息

**Comment by yenshih** [comment]
浏览器 `CustomElement` 机制与 polyfill 实现不完全相同
浏览器中 `attributeChangedCallback` 在前后属性相同的情况下，仍会触发
polyfill 中，前后属性相同时，不会触发该回调
iOS 8 浏览器不支持原生 `CustomElement`，降级到 polyfill 导致问题发生
