### ISSUE TITLE
【mip-viz-vega】IOS8下图表加载异常

### ISSUE THREAD

**Issue by liujing50** [mipengine/mip2-extensions#618]
**BUG 描述**
新增的mip-viz-vega组件，在IOS8系统下加载异常

**复现步骤**
重新复现 Bug 的步骤
1. ios8系统下，打开任意浏览器
2. 打开预览页面：https://deploy-preview-610--mip2-extensions-preview.netlify.com/examples/mip-viz-vega/mip-viz-vega.html
3. 图表无法加载

**期望结果**
正常显示

**截图**
![fc2ab9618880fbd77b505840f13a9db1](https://user-images.githubusercontent.com/48906158/56947608-43cc3680-6b60-11e9-881a-abf717c38e53.jpeg)
![b906a2ffff489bc2ef799385b2851667](https://user-images.githubusercontent.com/48906158/56947609-462e9080-6b60-11e9-8ddc-f87c3a987250.jpeg)

**环境及版本信息:**
 - OS: IOS8
 - 浏览器: 所有

**其他信息**
其他补充信息

**Comment by zoumiaojiang** [comment]
已修复，因为 vega 最新版 v5 的构建后的 JS 包含 async/await 语法，不兼容 iOS 8,9  等版本的浏览器。已经和 amp 同步，使用 vega@2.6.1 版本

**Comment by liujing50** [comment]
验证已修复
