### ISSUE TITLE
mip-scrollbox没有默认定位的功能

### ISSUE THREAD

**Issue by meilian7410** [mipengine/mip2-extensions#653]
**BUG 描述**
当页面进去的时候定位不到默认的那个data-item上

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by zoumiaojiang** [comment]
你好，能提供一个 url 看看具体怎么回事吗？或者能不能详细的描述一下你的需求以及现在的情况，以及你的预期是什么样的呢？

**Comment by meilian7410** [comment]
https://mm.91lovepei.xyz/gamelist/13.html
你看下,能不能定位到棋牌那个地方?




------------------ 原始邮件 ------------------
发件人: "zoumiaojiang"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 中午1:28
收件人: "mipengine/mip2-extensions"<mip2-extensions@noreply.github.com>;
抄送: "无所谓"<825814087@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mipengine/mip2-extensions] mip-scrollbox没有默认定位的功能 (#653)




你好，能提供一个 url 看看具体怎么回事吗？或者能不能详细的描述一下你的需求以及现在的情况，以及你的预期是什么样的呢？

**Comment by zoumiaojiang** [comment]
已支持该功能
