### ISSUE TITLE
mip-custom 中 from=noshell 的处理导致部分医疗页面不出广告

### ISSUE THREAD

**Issue by craigchencc** [mipengine/mip2-extensions#691]
**BUG 描述**
清晰和准确的描述 Bug 是什么
mip-custom 中 from=noshell 的处理导致部分医疗页面不出广告，主要场景是：搜索结果页打开不一定全是 mip cache 链接，还可能是源站链接。

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by craigchencc** [comment]
小说医疗统一了做法，暂时没有问题了

**Comment by sunhao-baikal** [comment]
@craigchencc 
场景：
搜索结果页打开源站链接，mip-custom 中 from=noshell 的处理导医疗页面不出广告，
页面信息：
Request URL: https://mipengine.baidu.com/common?logid.....
返回信息：errno: 10001, errmsg: "process error"
通过百度域打开没有问题，定制化组件内容正常加载，这是什么原因呢？谢谢
